### ISSUE TITLE
Design for durability

### ISSUE THREAD

**Issue by ghost** [aperturerobotics/nion#1]
Been thinking about something like this also.
Pretty nice what you have so far. But i a still getting familiar with its architecture as its pretty different approach.

For mutations, that result in a change to a query, what do you imagine will be needed in terms of a backing store ?
https://github.com/rgraphql/nion/blob/master/qtree/qtree.go
- your putting it in the variable store at the moment.

What would be the design implications for durable storage that is SQL or NOSQL ?

**Comment by paralin** [comment]
I have to say I missed this message. My apologies!

Durable storage could be implemented as a code generation layer. So, you might want to have an ORM that maps different queries to SQL calls or graphdb relations, say. This could be done as a code generation step, which generates code which is compatible with nion's resolver patterns. Then you can use the nion generator to build the resolver execution mapping.

**Comment by paralin** [comment]
Not sure exactly how to approach mutations yet. I think it'll be some other part of the protocol that ensures the entire query is synced through before the request can begin.
